# Generated by Django 2.2.5 on 2019-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191026_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
